default: preselectionControlPlots

include ../../backgroundEstimation/common/common.make

#--------------------------------------------------------------------------

preselectionControlPlots: preselectionControlPlots.$(ExeSuf)
	./preselectionControlPlots.$(ExeSuf)


